# Generated by Django 3.0.4 on 2020-04-01 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Sex',
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.CharField(default=None, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Star',
            },
        ),
        migrations.CreateModel(
            name='StarUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Star')),
            ],
            options={
                'verbose_name_plural': 'Star User',
            },
        ),
    ]
