# Generated by Django 3.0.4 on 2020-03-31 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_star_img_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sex',
            options={'verbose_name_plural': 'Sex'},
        ),
        migrations.AlterModelOptions(
            name='star',
            options={'verbose_name_plural': 'Star'},
        ),
        migrations.AlterModelOptions(
            name='staruser',
            options={'verbose_name_plural': 'Star User'},
        ),
        migrations.RenameField(
            model_name='star',
            old_name='img_url',
            new_name='image',
        ),
    ]
