# Generated by Django 3.0.4 on 2020-03-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200331_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='image',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
