# Generated by Django 3.0.4 on 2020-03-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200331_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='image',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
