# Generated by Django 3.0.4 on 2020-03-31 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200331_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='sex_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Sex'),
        ),
    ]
